# Generated by Django 4.0.4 on 2022-05-20 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.vendor', verbose_name='Вендор'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='response',
            field=models.IntegerField(blank=True, choices=[(1, 'waiting'), (2, 'on may way'), (3, 'denied')], null=True, verbose_name='Ответ вендора'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'created'), (2, 'viewed'), (3, 'done')], default=1, verbose_name='Статус транзакции'),
        ),
    ]
